name: Verify

on:
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 18.x

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Setup credentials
        shell: bash
        id: 'setup-credentials'
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PUBLISH_TOKEN }}" >> .npmrc
          echo "@rss-engineering:registry=https://npm.pkg.github.com" >> .npmrc

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Build package
        run: npm run build
